# Thêm tập dữ liệu của bạn vào kho lưu trữ
git add "C:\Users\NAME\Downloads\SeoulBikeData.csv"

# Commit tập dữ liệu
git commit -m "Add dataset"

# Thêm remote origin cho kho lưu trữ trên GitHub
git remote add origin https://github.com/username/repository.git

# Đẩy tập dữ liệu lên GitHub
git push -u origin main
